on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Download content
        shell: sh
        if: runner.os == 'Linux'
        run: wget -O video.mp4 http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "."
